### ISSUE TITLE
[Bug] release 3.0.2.1 is not available at plugins.matomo.com

### ISSUE THREAD

**Issue by toredash** [matomo-org/plugin-DeviceDetectorCache#4]
```
curl https://plugins.matomo.org/api/2.0/plugins/DeviceDetectorCache/download/3.0.2.1
{"error":"Requested version does not exist."}
```

Downloading the release from GitHub includes many files not needed, e.g. tests/

**Comment by tsteur** [comment]
@toredash the correct URL is https://plugins.matomo.org/api/2.0/plugins/DeviceDetectorCache/download/3.0.2

**Comment by toredash** [comment]
@tsteur But the release page in GH states 3.0.2.1: https://github.com/matomo-org/plugin-DeviceDetectorCache/releases

I have a script that queries each Matomo plugins Github repo to get the latest release, then I fetch the plugin from plugins.matomo.org since that release does not include e.g. tests/.

I get it that 3.0.2.1 and 3.0.2 are almost identical, but if I could avoid writing a custom update check for plugin-DeviceDetectorCache that would be great.

Thanks

**Comment by tsteur** [comment]
@toredash that's not something we really support unfortunately. While this might work most of the time. it isn't guaranteed that it this always matches. You could use instead https://plugins.matomo.org/api/2.0/plugins/DeviceDetectorCache/download/latest

You could also append parameters like your PHP version or Matomo version `?matomo=3.12.0`

**Comment by toredash** [comment]
@tsteur thanks for showing me the the `latest` option, that will work. I just have to understand that a GitHub release isn't the same as an "official" plugin release.
