### ISSUE TITLE
"DeviceDetector\Cache\Cache" cannot be resolved

### ISSUE THREAD

**Issue by aurelient** [matomo-org/plugin-DeviceDetectorCache#9]
After upgrading to Matomo 3.14, I get the following error after logging in:

`Entry "DeviceDetector\Cache\Cache" cannot be resolved: the class is not instantiableFull definition:Object ( class = #NOT INSTANTIABLE# DeviceDetector\Cache\Cache scope = singleton lazy = false)`

Would you have any clue on the source of the problem ? And ways to solve it ?

The shortest url with the problem is : [mydomain.yy/matomo/index.php?module=CoreHome](mydomain.yy/matomo/index.php?module=CoreHome)

**Comment by tsteur** [comment]
Hi @aurelient 

can you check if your `config/global.php` is up to date and looks like this one?  https://raw.githubusercontent.com/matomo-org/matomo/3.x-dev/config/global.php

**Comment by aurelient** [comment]
Hi, thanks for the answer! 
line 82 was missing
` 'DeviceDetector\Cache\Cache' => DI\object('Piwik\DeviceDetector\DeviceDetectorCache')->constructor(86400),`

Adding it manually fixed the issue.

**Comment by tsteur** [comment]
Thanks for letting is now  👍  might need to check why the file wasn't updated when upgrading.

**Comment by aurelient** [comment]
You're welcome, let me know if you want to have a peek into some of the upgrade log files.
